name: Build MSFONT

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.0

    - name: Set up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: 3.11.5

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
      working-directory: ${{ github.workspace }}

    - name: Build MSFONT
      run: |
        pyinstaller --noconfirm --onedir --windowed --icon "Assets/ICON/Sv-003.ico" --name "MSFONT" --version-file "Other/version_msfont.txt" --add-data "C:\Users\$env:USERNAME\AppData\Roaming\Python\Python311\site-packages/customtkinter;customtkinter/" --add-data "src/main.py;." --add-data "Assets:Assets/"  "src/ui.py"

    - name: Move Assets folder and remove 'MARKDOWN' and 'ICON' folders
      run: |
        mv dist/MSFONT/_internal/Assets dist/MSFONT/
        rm -r dist/MSFONT/Assets/MARKDOWN
        rm -r dist/MSFONT/Assets/ICON
      shell: bash      

    - name: Upload MSFONT artifacts
      uses: actions/upload-artifact@v3.1.3
      with:
        name: MSFONT
        path: dist/MSFONT
